#Triggers
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
#Functions
jobs:
  #Build Job
  build:
    #Name of the job
    name: Build
    # The OS to run the job on
    runs-on: ubuntu-latest
    # Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.x
          cache: npm
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: dist
      - name: Display structure of uploaded files
        run: ls -R
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: autopurchase
      url: https://lnga.github.io/autopurchase-vite-project/
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
      - name: Deploy to gh pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOPURCHASE_VITE_ACCESS_TOKEN }}
          publish_dir: dist
